### ISSUE TITLE
Add israel this system AIS

### ISSUE THREAD

**Issue by Jilda1987** [Trinkle23897/tuixue.online-visa#72]
Hi from I experience u need use paid user and after than u can scan every 30 sec.
This better chose.

**Comment by Trinkle23897** [comment]
1. We have no such amount of money to enable all AIS places
2. The issue is from login. Even though you scan per 30 seconds, it will ultimately be kicked off by the system and need to re-login. If the login events are too much, the IP address will be banned forever. We just checked this morning that two servers are still being banned by the AIS system.

**Comment by Jilda1987** [comment]
From my experience must use resdtial proxy ip fast one, and delete cookies.
Maybe u can help with israel I will pay u just send me we chat.
+972547466005
Plase

**Comment by Trinkle23897** [comment]
Do you mean https://github.com/Ed1123/visa_web_scraper? We have already use this technique to fetch data.

**Comment by Jilda1987** [comment]
Ans it's work ?

**Comment by Trinkle23897** [comment]
It won't help this project and actually our version of crawler was developed earlier than this one.

**Comment by Jilda1987** [comment]
I also have a bot, if u want 5alk about this semd we chat

**Comment by Trinkle23897** [comment]
What's your email?

**Comment by Jilda1987** [comment]
Michaelpaster365@gmail.com

**Comment by Trinkle23897** [comment]
Oh I see a lot of email in spam... Sorry about that.
